// 创建一个包含所有背景链接的数组
var backgroundLinks = [
    "https://menmiaocy-my.sharepoint.com/personal/xiaoqvan_365_mengacg_com/_layouts/15/download.aspx?UniqueId=9317dc8d-5029-4924-a233-455d7848d82c&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWVubWlhb2N5LW15LnNoYXJlcG9pbnQuY29tQGM0Y2IxYzljLWUyNmQtNGUwYi1iY2EyLTcwNDEyNDU2ZmQ1NiIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTg2NTgyNjYiLCJleHAiOiIxNjk4NjYxODY2IiwiZW5kcG9pbnR1cmwiOiJYZGVpenQxanR0SkpiaVprWXlnWUQ3eXVqU29aeE8zQ0RaWmRjYnFlRjFrPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTU3IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJZMG1pczRyWDhFQ2w5ajFHTmhTMVZnPT0iLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRJd1pERm1NRE10WXpWaE1TMDBOalE1TFRrMVptTXRObUV4TXpNeVkyRTBNemM0IiwiYXBwX2Rpc3BsYXluYW1lIjoi6I635Y-WT25lRHJpdmXnm7Tpk74iLCJnaXZlbl9uYW1lIjoieGlhbyIsImZhbWlseV9uYW1lIjoicXZhbiIsImFwcGlkIjoiZDdiNDFhNTItNWJiMy00M2RmLWEyMGMtNjI1OWNiNmExODg2IiwidGlkIjoiYzRjYjFjOWMtZTI2ZC00ZTBiLWJjYTItNzA0MTI0NTZmZDU2IiwidXBuIjoieGlhb3F2YW5AMzY1Lm1lbmdhY2cuY29tIiwicHVpZCI6IjEwMDMyMDAyQjEzOTk2MkIiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMmIxMzk5NjJiQGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMucmVhZCBhbGxmaWxlcy53cml0ZSBhbGxwcm9maWxlcy5yZWFkIiwidHQiOiIyIiwiaXBhZGRyIjoiMjAuMTkwLjE0NC4xNzIifQ.4Az6CVAhwwlQRum47pH5vdtrwSNdMgOifzK1oSZRwA8&ApiVersion=2.0",
    "https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9tZW5taWFvY3ktbXkuc2hhcmVwb2ludC5jb20vOnU6L3AveGlhb3F2YW5fMzY1L0VZM2NGNU1wVUNSSm9qTkZYWGhJMkN3Ql9JUEowVDIwbDhudHZ4X2xtcG02aGc_ZT1PV1F2ck0.webp",
    "https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9tZW5taWFvY3ktbXkuc2hhcmVwb2ludC5jb20vOnU6L3AveGlhb3F2YW5fMzY1L0VlTW1EWW9fREpSRGdfOGdDWEZ4NG1vQjhqMXl3cnl4dlcwR0gwUVBwc242Z2c_ZT1CODY0Wko.webp",
    "https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9tZW5taWFvY3ktbXkuc2hhcmVwb2ludC5jb20vOnU6L3AveGlhb3F2YW5fMzY1L0VZclIyYTVhR1ZKQnYwQTBldU01bHNJQkh3VkdWQkRZUmlINmNtME1FMjYwSHc_ZT05alVmT3k.webp",
    "https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9tZW5taWFvY3ktbXkuc2hhcmVwb2ludC5jb20vOnU6L3AveGlhb3F2YW5fMzY1L0VVOUMwbllCSGR0RnJfT1dmMnRJTjNvQktHajFpT2JqS3dvTVFzSjJqT1Ruenc_ZT1qd0JCeTg.webp"
];

// 清除本地存储中的背景链接
localStorage.removeItem("backgroundLink");

// 尝试从本地存储中获取背景链接
var storedBackgroundLink = localStorage.getItem("backgroundLink");

// 如果本地存储中有背景链接，则使用它，否则随机选择一个
var selectedBackgroundLink = storedBackgroundLink || backgroundLinks[Math.floor(Math.random() * backgroundLinks.length)];

// 将选定的链接设置为背景图片
var bgElement = document.getElementById("bg");
bgElement.src = selectedBackgroundLink;

// 将选定的链接存储到本地
localStorage.setItem("backgroundLink", selectedBackgroundLink);