name: Run Python Script

on:
  manual:
    # 手动触发工作流
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests pytz

    - name: Run Python Script
      run: |
        python fanjv/FJ.py

    - name: Move generated HTML
      run: |
        mv FJ.html fanjv/

    - name: Push to Repository
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
