name: 更新番剧页面

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
        
    - name: Checkout代码
      uses: actions/checkout@v2

    - name: 设置Python环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # 输入你需要的Python版本

    - name: 安装 requests 模块
      run: pip install requests

    - name: 安装 pytz 模块
      run: pip install pytz

    - name: 运行自动更新脚本
      run: python fanjv/FJ.py

    - name: 移动文件到fanjv文件夹
      run: mv FJ.html fanjv/
      

    - name: Set up Git
      run: |
        git config user.name 'XQxiaoqvan'
        git config user.email 'xiaoqvandd@qq.com'
    
    - name: Push to GitHub
      run: |
        git add fanjv/FJ.html
        git commit -m 'Update FJ.html'
        git push https://${{ secrets.GH_TOKEN }}@github.com/XQxiaoqvan/xqxiaoqvan.github.io.git HEAD:main
    