name: Generate HTML

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests pytz

    - name: Generate HTML
      run: python fanjv/FJ.py

    - name: Create HTML file
      run: echo "Generated HTML content" > fanjv/FJ.html
    
    - name: Debug Information
      run: |
        echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
        ls -al ~/.ssh
        cat ~/.ssh/id_rsa
        cat ~/.ssh/known_hosts
    
    

    - name: Commit and push changes
      run: |
        git config --local user.email "xiaoqvandd@qq.com"
        git config --local user.name "XQxiaoqvan"
        git add fanjv/FJ.html
        git commit -m "Generated FJ.html"
        git push git@github.com:XQxiaoqvan/xqxiaoqvan.github.io.git HEAD:${{ github.ref }}
    