name: 更新番剧页面

on:
  workflow_dispatch: # 手动触发
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout代码
      uses: actions/checkout@v2

    - name: 设置Python环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # 输入你需要的Python版本

    - name: 安装 requests 模块
      run: pip install requests

    - name: 安装 pytz 模块
      run: pip install pytz

    - name: 运行自动更新脚本
      run: python fanjv/FJ.py

    - name: 推送更新到 GitHub Pages 仓库
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: main  # 修改为你要推送到的分支
        repository: XQxiaoqvan/xqxiaoqvan.github.io  # 目标仓库
        directory: fanjv  # 本地目录
    