name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests pytz

    - name: Run Python Script
      run: |
        python fanjv/FJ.py

    - name: Move generated HTML
      run: |
        mv FJ.html fanjv/

    - name: Git Push
      run: |
        git config --local user.name "XQxiaoqvan"
        git config --local user.email "xiaoqvandd@qq.com"
        git add fanjv/FJ.html
        git commit -m "Generated FJ.html"
        git push https://XQxiaoqvan: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@github.com/XQxiaoqvan/xqxiaoqvan.github.io.git HEAD:main
